routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('slider', 'SliderController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('postingan', 'PostinganController');
});

// Route::get('/login', 'HomeController@login');
Route::get('/logout', 'HomeController@logout');

Route::get('/', 'BlogController@index');
Route::get('/detail/{slug}', 'BlogController@detail')->name('frontend.detail');
Route::get('/kontak', 'BlogController@kontak')->name('frontend.kontak');
Route::post('/detail/{slug}', 'BlogController@tampil')->name('frontend.detail');
Route::get('/cari', 'BlogController@cari')->name('frontend.cari');

app/Postingan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Postingan extends Model
{
    protected $table = 'postingan';

    protected $fillable = ['judul', 'deskripsi', 'kategori_id', 'tag', 'users_id', 'slug', 'gambar'];

    public function users()
    {
        return $this->belongsTo('App\User');
    }

    public function kategori()
    {
        return $this->belongsTo('App\Kategori');
    }

    public function komentar()
    {
        return $this->hasMany('App\Komentar');
    }
}

app/Http/Controllers/PostinganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Postingan;
use App\Kategori;
use Illuminate\Support\Facades\Auth;

class PostinganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // lakukan join agar menampilkan field slug pada tabel kategori dengan tabel postingan
        $kategori = Kategori::all();
        $postingan = Postingan::latest()->paginate(10);
        return view('admin.postingan.index', compact('kategori', 'postingan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = Kategori::all();
        return view('admin.postingan.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul'         => 'required',
            'deskripsi'     => 'required',
            'kategori_id'   => 'required',
            'tag'           => 'required',
            'gambar'        => 'required|image|mimes:jpg,png,jpeg|max:2048'
        ]);

        $gambar = $request->gambar;

        $gambar_post = time() . $gambar->getClientOriginalName();

        $postingan = Postingan::create([
            'judul' => $request->judul,
            'deskripsi' => $request->deskripsi,
            'kategori_id' => $request->kategori_id,
            'tag' => $request->tag,
            'slug' => Str::slug($request->judul),
            'gambar' => 'public/uploads/post/' . $gambar_post,
            'users_id' => Auth::id()
        ]);

        $gambar->move('public/uploads/post/', $gambar_post);

        return redirect()->route('postingan.index')->with('toast_success', 'Postingan Berhasil di tambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // lakukan join agar menampilkan field nama_kategori pada tabel kategori dengan tabel postingan
        $postingan = Postingan::find($id);
        $kategori = Kategori::all();
        return view('admin.postingan.edit', compact('postingan', 'kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'judul' => 'required',
            'deskripsi' => 'required',
            'kategori_id' => 'required',
            'tag' => 'required'

        ]);
        $postingan = Postingan::findorfail($id);

        if ($request->has('gambar')) {
            $gambar_post = $request->gambar;
            $gambar_post_baru = time() . $gambar_post->getClientOriginalName();
            $gambar_post->move('public/uploads/post/', $gambar_post_baru);

            $post_data = [
                'judul'         => $request->judul,
                'deskripsi'     => $request->deskripsi,
                'kategori_id'   => $request->kategori_id,
                'tag'           => $request->tag,
                'slug'          => Str::slug($request->judul),
                'gambar'        => 'public/uploads/slider/' . $gambar_post_baru
            ];
        } else {
            $post_data = [
                'judul'         => $request->judul,
                'deskripsi'     => $request->deskripsi,
                'kategori_id'   => $request->kategori_id,
                'tag'           => $request->tag,
                'slug'          => Str::slug($request->judul)
            ];
        }

        $postingan->update($post_data);

        return redirect()->route('postingan.index')->with('toast_success', 'Postingan Berhasil di edit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $postingan = Postingan::destroy($id);

        return redirect()->route('postingan.index')->with('toast_success', 'Postingan Berhasil di hapus!');
    }
}

resources/views/admin/postingan/create.blade.php
@extends('backend.konten')

@section('judul', 'Tambah Postingan')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('postingan.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Judul postingan</label>
                            <input type="text" class="form-control" name="judul" id="formGroupExampleInput" placeholder="Masukkan Judul Postingan">
                        </div>

                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Deskripsi</label>
                            <textarea class="form-control" name="deskripsi" id="deskripsi" placeholder="Masukkan Deskripsi"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Kategori yang Berkaitan</label>
                            <select class="form-control select2 select2-hidden-accessible" name="kategori_id" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                <option selected="selected" data-select2-id="">Pilih Kategori</option>
                                @foreach ($kategori as $item)
                                <option data-select2-id="{{$item->id}}" value="{{$item->id}}">{{$item->nama_kategori}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Tag postingan</label>
                            <input type="text" class="form-control" name="tag" id="formGroupExampleInput" placeholder="Masukkan Tag Postingan">
                        </div>

                        <div class="form-group">
                            <label for="exampleFormControlFile1">File Gambar</label>
                            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="gambar">
                        </div>
                        <a href="{{route('postingan.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                        <button type="submit" class="btn btn-success btn-sm">Simpan postingan</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'deskripsi' );
</script>

@endsection

resources/views/admin/postingan/edit.blade.php
@extends('backend.konten')

@section('judul', 'Edit Postingan')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('postingan.update', $postingan->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="formGroupExampleInput">Edit Judul Postingan</label>
                            <input type="text" class="form-control" value="{{$postingan->judul}}" name="judul" id="formGroupExampleInput" placeholder="Masukkan Judul Postingan">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Edit Deskripsi</label>
                            <textarea type="text" class="form-control" name="deskripsi" id="deskripsi" placeholder="Masukkan Deskripsi">{{$postingan->deskripsi}}</textarea>
                        </div>
                        <div class="form-group">
                            <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Edit Kategori</label>
                            <select class="custom-select my-1 mr-sm-2" name="kategori_id" id="inlineFormCustomSelectPref">
                                <option selected>Pilih Kategori</option>
                                @foreach ($kategori as $item)
                                <option value="{{$item->id}}" @if ($postingan->kategori_id == $item->id)
                                    selected
                                    @endif
                                    >{{$item->nama_kategori}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="formGroupExampleInput">Edit Tag Postingan</label>
                            <input type="text" class="form-control" value="{{$postingan->tag}}" name="tag" id="formGroupExampleInput" placeholder="Masukkan Judul Postingan">
                        </div>

                        <div class="form-group">
                            <label for="exampleFormControlFile1">File Gambar</label>
                            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="gambar">
                        </div>

                        <div class="form-group">
                            <img src="{{asset($postingan->gambar)}}" width="30%" height="30%">
                        </div>
                        <a href="{{route('postingan.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                        <button type="submit" class="btn btn-success btn-sm">Simpan postingan</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'deskripsi' );
</script>
@endsection

resources/views/admin/postingan/index.blade.php
@extends('backend.konten')

@section('judul', 'postingan')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-2">
            <div class="card mt-2">
                <div class="card-header">
                    <a href="{{route('postingan.create')}}" class="btn btn-primary">Tambah postingan</a>
                </div>
                <div class="card-body">

                    {{-- Kategori yang disimpan hanya bisa disimpan 1 kali --}}
                    <table class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Judul</th>
                                <th scope="col">Deskripsi</th>
                                <th scope="col">Kategori</th>
                                <th scope="col">Tag</th>
                                <th scope="col">Slug</th>
                                <th scope="col">Penulis</th>
                                <th scope="col">Gambar</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($postingan as $item => $hasil)
                            <tr>
                                <th scope="row">{{$loop->iteration}}</th>
                                <td>{{$hasil->judul}}</td>
                                <td>{!!substr($hasil->deskripsi, 0, 25) !!}</td>
                                <td><em>#{{$hasil->kategori->nama_kategori}}</em></td>
                                <td> {{$hasil->tag}}
                                </td>
                                <td><em>{{$hasil->slug}}</em></td>
                                <td>{{$hasil->users->name}}</td>
                                <td width="15%"><img src="{{asset( $hasil->gambar )}}" alt="{{$hasil->judul}}" style="width:150px;"></td>
                                <td width="10%">
                                    <form action="{{route('postingan.destroy',$hasil->id)}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <a href="{{route('postingan.edit', $hasil->id)}}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                        <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{$postingan->links()}}
                </div>
            </div>
        </div>
    </div>
</div>

@include('sweetalert::alert')

@endsection